config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes do 
    resources :ingredients 

  end
  resources :ingredients_recipes

  
    
  

  get '/' => "sites#index"
  get '/homepage' => "sites#homepage" , as: :user_root

  post '/search' => "ingredients#search"

 

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	has_and_belongs_to_many :recipes
	

	accepts_nested_attributes_for :ingredients_recipes, :allow_destroy => true

	# def self.search(search)
	# binding.pry
	#   Ingredient.where("name LIKE ?", "%#{search}%") 	
	# end
	
	def self.get_all_ingredients
		Ingredient.all.collect! {|ingredient| ingredient.name}
	end

	def self.get_ingredient_id(ingredient)
		Ingredient.where(name: "#{ingredient}")[0].id
	end
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base

	belongs_to :recipe
	
	belongs_to :ingredient



	def self.get_ingredients_for_recipe(recipe_id)
		IngredientsRecipe.where(recipe_id: recipe_id).collect {|object| Ingredient.find(object.ingredient_id)}
	end

	#def self.get_quantities_and_measures(ingredient_id)

	#	@quantities_measures = @ingredients.each do |ing_id|
	#		ing_id.id
			
	#	end
		#RecipeWithIngredient.find(ingredient_id)
		#binding pry
	#end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_and_belongs_to_many :ingredients

	validates_attachment :image,
                     image_content_type: { image_content_type: ["image/jpeg", "image/png"] }
	#scope :by_time, lambda{ |time| where(time: time.to_i) unless type.nil? }

	#scope :time, -> (time) { where time: time }
	
	
end

app/models/recipe_with_ingredient.rb
class RecipeWithIngredient < ActiveRecord::Base
	belongs_to :ingredient
	belongs_to :recipe

	def self.get_ingredients_for_recipe(recipe_id)

		 @ingredients = []
		 @ingredients << Ingredient.find(RecipeWithIngredient.where(recipe_id)[0].ingredient_id)

	end

	#def self.get_quantities_and_measures(ingredient_id)

	#	@quantities_measures = @ingredients.each do |ing_id|
	#		ing_id.id
			
	#	end
		#RecipeWithIngredient.find(ingredient_id)
		#binding pry
	#end






end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :city
    devise_parameter_sanitizer.for(:sign_up) << :about
  end

  

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def search
		name = params[:ingredient].downcase
		if ingredient = Ingredient.find_by(name: name)#this gets the name from ingredient 
			@recipes = ingredient.recipes
		end		
	
	end

	def new
		@ingredient = Ingredient.new
		@ingredient.ingredients_recipes.build		
	end
	


	def create
		
		if Recipe.last.step == 2
			Ingredient.create(name: params[:ingredient][:name])
			IngredientsRecipe.create(
				measure: params[:ingredients_recipe][:measure],
				quantity: params[:ingredients_recipe][:quantity],
				ingredient_id: Ingredient.last.id,
				recipe_id: params[:recipe_id]
				)

		end
		redirect_to new_recipe_path

    end

	def show
		@ingredient = Ingredient.find(params[:id]) 	
	end

	def ingredient_params
	    params.require(:ingredients).permit(:name).downcase
  	end
end

app/controllers/ingredients_recipes_controller.rb
class IngredientsRecipesController < ApplicationController

	def show
		@recipe_with_ingredients = IngredientsRecipe.find(recipe_with_ingredients_params)
	end 

	def new 
		@amount = RecipeWithIngredients.new
	end

	def create	
		qty = params[:recipe_with_ingredient][:quantity]
		measure = params[:recipe_with_ingredient][:measure]
		recipe_id = params[:recipe_with_ingredient][:recipe_id]
		recipe_with_ingredients = RecipeWithIngredient.new(quantity: qty, measure: measure, recipe_id: recipe_id)
		recipe_with_ingredients.ingredient_id = Ingredient.get_ingredient_id(params[:recipe_with_ingredient][:ingredient_id])
		recipe_with_ingredients.save
		
		recipe = Recipe.last
		redirect_to new_recipe_path	
	end

	private 

	# def recipe_with_ingredient_params
	#      params.require(:recipes_with_ingredient).permit(
	#        :recipe_id,  :quantity, :measure)
 #  	end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	

	def new
		if Recipe.last.step == 3 || Recipe.last.step == 1
			@new_recipe = Recipe.new
		else 
			@recipe = Recipe.last
			@ingredient = Ingredient.new
			@ingredients_recipes = IngredientsRecipe.new
			@added_ingredients = @recipe.ingredients
		end
		#PARA USAR NESTED FORMS----------------
		#@recipe.ingredients.build # build ingredient attributes, nothing new here
	end

	def index
		@recipes = Recipe.all
	end

	def create
		recipe = Recipe.new(recipe_params)
		recipe.step = 2
		if recipe.save
			redirect_to new_recipe_path
		else 
			flash[:notice] = recipe.errors.full_messages.to_sentence
		end
	end

	def show
		@recipe = Recipe.find(params[:id])
	end 

	def edit
		@recipe = Recipe.find(params[:id])
		if @recipe.step != 2
			redirect_to new_recipe_path
		end
	end


	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.step == 2
			@recipe.update(recipe_params)
			@recipe.update(step: 3)
			flash[:message] = "Recipe Created!!"
		else 
			@recipe.update(recipe_params)
		end
		redirect_to recipe_path(@recipe)
    end
		

   	private 

	def recipe_params
	    params.require(:recipe).permit(
	    	:id, :time, :title, :preparation, :image)
  	end


  	# def ingredient_params
	  #   params.require(:ingredient).permit(
	  #   	:id, :name)
  	# end

  	# def recipe_with_ingredient_params
  	# 	params.require(:recipe_with_ingredient).permit(
  	# 		:id, :recipe_id, :ingredient_id, :quantity, :measure)
  	# end 	
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	def index
	end

	def homepage
		@ingredient = Ingredient.select(:id)
	end

	def search
		
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/ingredients_recipes_helper.rb
module IngredientsRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/new.html.erb
  
   	<%= f.label :name %>
    <%br%>
  	<%= f.text_field :name %>
 
   	<%= f.submit 'Add ingredient', :name => "add_ingredient" %>
   	<%= link_to_remove_association "remove ingredient", f %>

app/views/ingredients/search.html.erb
	
<div class='search_container_background'>
	<div class='navbar'>
    	<div id="logo">
        	<a href="/homepage">
        	<span class='logo_text'>
        	chop- <br> -chop</span></a>  
    	</div>
  	</div> 

	<div class= 'search-container'>

	<% if @recipes %>
		<h4 class= 'list-of-recipes-title'>Here are some ideas!</h4>

		<ul class ='list_of_recipes'>
			<% @recipes.each do |recipe| %>
			<li> <%= link_to recipe.title, recipe_path(recipe.id)%></li>
		<% end %>
		
		</ul>	
	</div>	
	<% else %>
		<p id='nothing'>Nothing found :(</p>

	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalProject</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Just+Another+Hand' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/edit.html.erb
<div class='create_preparation_background'>
	
		<div class='navbar'>
	    	<div id="logo">
	      		<a href="/homepage">
	      		<span class='logo_text'>
	      		chop- <br> -chop</span></a>  
	    	</div>
	  	</div>    
	<div class='create_preparation'>
		<div class='preparation_form'>
			<% if @recipe %>
				<%= form_for @recipe  do |f| %>
						  <%= f.label :preparation %>:<br>
						  <%= f.text_area :preparation %><br>
						  <%= f.label :image %>
    					<%= f.file_field :image, class: 'form-control'%>
						  
						  <br>
						  <%= f.submit "Done!" %>
				<% end %>	
			<% else %>
				<%= form_for @recipe_last_step do |f| %>
						  <%= f.label :preparation %><br>
						  <%= f.text_area :preparation %><br/>
						  <%= f.label :image %>
    					<%= f.file_field :image, class: 'form-control'%>
    					<br>

						  <%= f.submit "Done!" %>
				<% end %>	
			<% end %>

		</div>

			
	</div>	
</div>

app/views/recipes/new.html.erb
<div class='create_recipe_background'>
  
  <div class='navbar'>
    <div id="logo">
        <a href="/homepage">
        <span class='logo_text'>
        chop- <br> -chop</span></a>  
    </div>
  </div>    

  <div class= 'create_recipe_form'>
    <div class="left-half">
      <div class='create_title_time'>
        <% if @new_recipe %> 
          <h1>New recipe</h1> 
            <%= form_for @new_recipe do |f| %>
           
              <%= f.label :title %><br />
              <%= f.text_field :title %>
          
              <br>
              <%= f.label :time %><br />
              <%= f.select :time, options_for_select([15, 30])%>
            <br>
            <br>
              <%= f.submit 'Next' %>
            <% end %>
        </div>  
      <% else %> 
        <h3 >Ingredients</h3>
        <%= form_for [@recipe, @ingredient] do |ing| %>
        <p>
          <%= ing.label :name %><br>
          <%= ing.text_field :name %><br>
          <%= fields_for @ingredients_recipes do |details| %> 
            <%= details.label :quantity %><br>
            <%= details.number_field :quantity %><br>
            <%= details.label :measure %><br>
            <%= details.text_field :measure %>
          <% end %>
        </div>  
          </p>
          <p>
          <%= ing.submit 'Add ingredient', :name => "add_ingredient" %>  
          </p>

      <% end %>
    <% end %>
    </div>
    <% if @recipe %>
    <div class="right-half">
      <h3>List of Ingredients</h3>
      <ul> <% @added_ingredients.each do |ingredient| %>
        <li><%= ingredient.name %></li>
      <ul>  
      <% end %>
    </div>

    
      <button class='next_step'><%= link_to "next step", edit_recipe_path(@recipe) %></button>
    <% end %>

</div> 

app/views/recipes/show.html.erb
<div class='show_recipe_background'>
	<div class='navbar'>
    	<div id="logo">
        <a href="/homepage">
        <span class='logo_text'>
        chop- <br> -chop</span></a>  
    	</div>
  	</div> 


  	<div class= 'show_container'>

		<div class='show_recipe_page'>
			<div id= 'recipe'>
				<h3> <%= @recipe.title %> </h3>



				<h4> It will take you <%= @recipe.time %> minutes! </h4>

				<p> Preparation <%= @recipe.preparation %> </p>
			</div>
		</div>	

		
		<div class='show_ingredients_page'>
			<div id='list_of_ingredients'>

			<h3>Ingredients</h3>	
			<ul><% @recipe.ingredients.each do |ingredient| %>

				<li><%= ingredient.name %></li>	
			<% end %>
			</ul>

			</div>

			<%= link_to "Home", user_root_path%>
		</div>
	</div>
</div>

app/views/sites/homepage.html.erb
<div class = 'homepage-background'>
	<div class='container-homepage'>
		<div class= 'search-page'>
			<div class ='search-form'>
				<%= form_tag('/search') do %>
					<label for="ingredient">What's in your fridge?</label>
					<div><%= text_field_tag 'ingredient'%></div>
					<div class='minutes_selector'>
						 <label><input type="radio" name="filter" value='15'checked="checked" /> 15'</label>
						 <label><input type="radio" name="filter" value='30' checked="checked" /> 30'</label>
					 </div>
			  		<div class= "submit"><%= submit_tag 'Submit' %></div>

				<% end %>
			</div>	
		</div>
		</form>
		<button class='new_recipe'><%= link_to "new recipe", new_recipe_path %></button>
	</div>
</div>	

<script type="text/javascript">
	$("input[type='radio']").change(function () {
	    var time = $("[name='time']:checked").val();

	    if (!time || !time) return;
	    $("li").hide();
	    $("li").filter(function (index) {
	        return $(this).hasClass(time)
	   	}).show();
	});
</script>	

app/views/sites/index.html.erb
<div class='container_front_page'>
	
<div class= 'navbar'>

	<div id="logo">
		<span class='logo_text'>
		chop- <br> -chop</span>	
	</div>	

	<div class='sign_buttons'>
		<button class='signin'><%= link_to "sign in", new_user_session_path %></button>
		<button class='signup'><%= link_to "sign up", new_user_registration_path %></button>
	</div>
	
</div>